# Generated by Django 5.2.7 on 2026-05-18 14:47

import django.db.models.deletion
from django.db import migrations, models


# === 1. FUNCIONES DE CARGA DE DATOS (Afuera de la clase) ===

def cargar_5_empleados_y_clientes(apps, schema_editor):
    Supermercado = apps.get_model('appsuper', 'Supermercado')
    Sucursal = apps.get_model('appsuper', 'Sucursal')
    Empleado = apps.get_model('appsuper', 'Empleado')
    Cliente = apps.get_model('appsuper', 'Cliente')
    Jefe = apps.get_model('appsuper', 'Jefe')

    super_ar, _ = Supermercado.objects.get_or_create(
        pais="Argentina",
        defaults={'ano_fundacion': 2026, 'cant_sucursales': 5}
    )

    sucursales_data = [
        {"id_sucursal": 1, "nombre": "Sede Almagro", "domicilio": "Venezuela 4343"},
        {"id_sucursal": 2, "nombre": "Sede Da Vinci", "domicilio": "Av. Corrientes 2037"},
        {"id_sucursal": 3, "nombre": "Sede Abasto", "domicilio": "Av. Corrientes 3247"},
        {"id_sucursal": 4, "nombre": "Sede Plaza Miserere (Once)", "domicilio": "Av. Rivadavia 2800"},
        {"id_sucursal": 5, "nombre": "Sede San Cristóbal", "domicilio": "Av. San Juan 3200"},
    ]

    sucursales_creadas = {}
    for suc in sucursales_data:
        instancia_suc, _ = Sucursal.objects.get_or_create(
            id_sucursal=suc['id_sucursal'],
            defaults={
                'supermercado': super_ar, 
                'nombre': suc['nombre'], 
                'domicilio': suc['domicilio'], 
                'localidad': f"{suc['nombre']} - {suc['domicilio']}" 
            }
        )
        sucursales_creadas[suc['id_sucursal']] = instancia_suc

    empleados_data = [
        {'id_empleado': 1, 'nombre': 'Juan Pérez', 'sexo': 'hombre', 'dni': 44640649, 'edad': 23, 'anos_servicio': 1, 'sueldo': 1000.0, 'sucursal_id': 1},
        {'id_empleado': 2, 'nombre': 'Andrés Silva', 'sexo': 'hombre', 'dni': 42111222, 'edad': 26, 'anos_servicio': 3, 'sueldo': 1150.0, 'sucursal_id': 1},
        {'id_empleado': 3, 'nombre': 'Sofía Castro', 'sexo': 'mujer', 'dni': 43555666, 'edad': 24, 'anos_servicio': 2, 'sueldo': 1050.0, 'sucursal_id': 1},
        {'id_empleado': 4, 'nombre': 'María Rodríguez', 'sexo': 'mujer', 'dni': 41234567, 'edad': 28, 'anos_servicio': 4, 'sueldo': 1200.0, 'sucursal_id': 2},
        {'id_empleado': 5, 'nombre': 'Diego Fernández', 'sexo': 'hombre', 'dni': 39888777, 'edad': 32, 'anos_servicio': 6, 'sueldo': 1500.0, 'sucursal_id': 2},
        {'id_empleado': 6, 'nombre': 'Lucía Morales', 'sexo': 'mujer', 'dni': 45222333, 'edad': 22, 'anos_servicio': 1, 'sueldo': 980.0, 'sucursal_id': 2},
        {'id_empleado': 7, 'nombre': 'Carlos López', 'sexo': 'hombre', 'dni': 38987654, 'edad': 35, 'anos_servicio': 8, 'sueldo': 1800.0, 'sucursal_id': 3},
        {'id_empleado': 8, 'nombre': 'Laura Benítez', 'sexo': 'mujer', 'dni': 37444555, 'edad': 38, 'anos_servicio': 10, 'sueldo': 2100.0, 'sucursal_id': 3},
        {'id_empleado': 9, 'nombre': 'Gabriel Herrera', 'sexo': 'hombre', 'dni': 40666777, 'edad': 31, 'anos_servicio': 5, 'sueldo': 1450.0, 'sucursal_id': 3},
        {'id_empleado': 10, 'nombre': 'Ana Martínez', 'sexo': 'mujer', 'dni': 45112233, 'edad': 21, 'anos_servicio': 2, 'sueldo': 950.0, 'sucursal_id': 4},
        {'id_empleado': 11, 'nombre': 'Martín Díaz', 'sexo': 'hombre', 'dni': 41999888, 'edad': 29, 'anos_servicio': 4, 'sueldo': 1300.0, 'sucursal_id': 4},
        {'id_empleado': 12, 'nombre': 'Elena Gómez', 'sexo': 'mujer', 'dni': 43888999, 'edad': 25, 'anos_servicio': 3, 'sueldo': 1100.0, 'sucursal_id': 4},
        {'id_empleado': 13, 'nombre': 'Luis Gómez', 'sexo': 'hombre', 'dni': 40445566, 'edad': 30, 'anos_servicio': 5, 'sueldo': 1400.0, 'sucursal_id': 5},
        {'id_empleado': 14, 'nombre': 'Valeria Ortiz', 'sexo': 'mujer', 'dni': 36555444, 'edad': 40, 'anos_servicio': 12, 'sueldo': 2500.0, 'sucursal_id': 5},
        {'id_empleado': 15, 'nombre': 'Santiago Ruiz', 'sexo': 'hombre', 'dni': 44111000, 'edad': 23, 'anos_servicio': 1, 'sueldo': 1000.0, 'sucursal_id': 5},
    ]

    for emp in empleados_data:
        Empleado.objects.get_or_create(
            id_empleado=emp['id_empleado'],
            defaults={
                'nombre': emp['nombre'],
                'sexo': emp['sexo'], 
                'sucursal': sucursales_creadas[emp['sucursal_id']],
                'dni': emp['dni'],
                'edad': emp['edad'],
                'anos_servicio': emp['anos_servicio'],
                'sueldo': emp['sueldo']
            }
        )

    jefes_data = [
        {'sucursal_id': 1, 'dni': 42111222, 'edad': 26, 'anos_servicio': 3},  # Andrés Silva (Sucursal 1)
        {'sucursal_id': 2, 'dni': 39888777, 'edad': 32, 'anos_servicio': 6},  # Diego Fernández (Sucursal 2)
        {'sucursal_id': 3, 'dni': 37444555, 'edad': 38, 'anos_servicio': 10}, # Laura Benítez (Sucursal 3)
        {'sucursal_id': 4, 'dni': 41999888, 'edad': 29, 'anos_servicio': 4},  # Martín Díaz (Sucursal 4)
        {'sucursal_id': 5, 'dni': 36555444, 'edad': 40, 'anos_servicio': 12}, # Valeria Ortiz (Sucursal 5)
    ]

    for jef in jefes_data:
        Jefe.objects.get_or_create(
            dni=jef['dni'],
            defaults={
                'edad': jef['edad'],
                'anos_servicio': jef['anos_servicio'],
                'sucursal_id': jef['sucursal_id'],  # Pasamos explícitamente el valor entero del atributo
                'sucursal': sucursales_creadas[jef['sucursal_id']]
            }
        )

    clientes_data = [
        {'id_cliente': 1, 'nombre': 'Santiago Silva', 'sexo': 'hombre', 'dni': 99999999, 'edad': 30, 'dinero': 5500.0},
        {'id_cliente': 2, 'nombre': 'Florencia Benítez', 'sexo': 'mujer', 'dni': 95555444, 'edad': 45, 'dinero': 12000.50},
        {'id_cliente': 3, 'nombre': 'Tomás Castro', 'sexo': 'hombre', 'dni': 93333222, 'edad': 19, 'dinero': 450.0},
        {'id_cliente': 4, 'nombre': 'Elena Espinoza', 'sexo': 'mujer', 'dni': 92222111, 'edad': 62, 'dinero': 25000.0},
        {'id_cliente': 5, 'nombre': 'Bautista Peralta', 'sexo': 'hombre', 'dni': 91111000, 'edad': 27, 'dinero': 150.75},
    ]

    for cli in clientes_data:
        Cliente.objects.get_or_create(
            id_cliente=cli['id_cliente'],
            defaults={
                'nombre': cli['nombre'],
                'sexo': cli['sexo'], 
                'dni': cli['dni'],
                'edad': cli['edad'],
                'dinero': cli['dinero']
            }
        )

def cargar_productos_supermercado(apps, schema_editor):
    Producto = apps.get_model('appsuper', 'Producto')

    productos_data = [
        {'id_producto': 1, 'nombre': 'Pack de Galletitas Sonrisas Nutrileche de Frambuesa', 'costo': 1200.0, 'peso': 0.15, 'categoria': 'Golosinas', 'stock': 50, 'imagen': 'productos/sonrisas.webp', 'empresa': 'Arcor'},
        {'id_producto': 2, 'nombre': 'Pack x3 Galletitas Criollitas', 'costo': 1800.0, 'peso': 0.30, 'categoria': 'Golosinas', 'stock': 40, 'imagen': 'productos/criollitas.jpg', 'empresa': 'Bagley'},
        {'id_producto': 3, 'nombre': 'Fideos Tallarín Lucchetti', 'costo': 1100.0, 'peso': 0.50, 'categoria': 'Almacén', 'stock': 100, 'imagen': 'productos/fideos.webp', 'empresa': 'Molinos Río de la Plata'},
        {'id_producto': 4, 'nombre': 'Botella de Agua Mineral Villavicencio 2L', 'costo': 1300.0, 'peso': 2.0, 'categoria': 'Bebidas', 'stock': 80, 'imagen': 'productos/agua.webp', 'empresa': 'Danone'},
        {'id_producto': 5, 'nombre': 'Vino Tinto Malbec Alamos 750ml', 'costo': 5500.0, 'peso': 0.75, 'categoria': 'Bebidas', 'stock': 25, 'imagen': 'productos/vino.jpg', 'empresa': 'Catena Zapata'},
        {'id_producto': 6, 'nombre': 'Coca Cola Original 2.25L', 'costo': 2800.0, 'peso': 2.25, 'categoria': 'Bebidas', 'stock': 60, 'imagen': 'productos/cocacola.jpg', 'empresa': 'The Coca-Cola Company'},
        {'id_producto': 7, 'nombre': 'Leche Entera La Serenísima 1L', 'costo': 1400.0, 'peso': 1.0, 'categoria': 'Lácteos', 'stock': 45, 'imagen': 'productos/leche.jpg', 'empresa': 'Mastellone Hermanos'},
        {'id_producto': 8, 'nombre': 'Manteca Sancor 200g', 'costo': 1900.0, 'peso': 0.20, 'categoria': 'Lácteos', 'stock': 30, 'imagen': 'productos/manteca.jpg', 'empresa': 'SanCor'},
        {'id_producto': 9, 'nombre': 'Shampoo Sedal Ceramidas 400ml', 'costo': 2100.0, 'peso': 0.40, 'categoria': 'Perfumería', 'stock': 35, 'imagen': 'productos/shampoo.jpg', 'empresa': 'Unilever'},
        {'id_producto': 10, 'nombre': 'Jabón de Tocador Lux Rosas Francesas Pack x3', 'costo': 2900.0, 'peso': 0.375, 'categoria': 'Perfumería', 'stock': 45, 'imagen': 'productos/jabon.jpg', 'empresa': 'Unilever'},
        {'id_producto': 11, 'nombre': 'Detergente Multiuso Magistral Limón 500ml', 'costo': 2300.0, 'peso': 0.50, 'categoria': 'Limpieza', 'stock': 70, 'imagen': 'productos/detergente.webp', 'empresa': 'Procter & Gamble'},
        {'id_producto': 12, 'nombre': 'Agua Lavandina Común Ayudín Original 1L', 'costo': 1150.0, 'peso': 1.0, 'categoria': 'Limpieza', 'stock': 90, 'imagen': 'productos/lavandina.jpg', 'empresa': 'The Clorox Company'},
    ]

    for prod in productos_data:
        Producto.objects.get_or_create(
            id_producto=prod['id_producto'],
            defaults={
                'nombre': prod['nombre'],
                'costo': prod['costo'],
                'peso': prod['peso'],
                'categoria': prod['categoria'],
                'stock': prod['stock'],
                'imagen': prod['imagen'],
                'empresa': prod['empresa']
            }
        )



# === 2. CLASE DE MIGRACIÓN PRINCIPAL ===

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin Nombre', max_length=150)),  # AGREGADO
                ('sexo', models.CharField(default='hombre', max_length=10)),         # AGREGADO
                ('edad', models.IntegerField()),
                ('dni', models.IntegerField(unique=True)),
                ('id_cliente', models.IntegerField(unique=True)),
                ('dinero', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pasillo', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sede Central', max_length=150)), # AGREGADO
                ('domicilio', models.CharField(default='Dirección', max_length=200)),  # AGREGADO
                ('localidad', models.CharField(max_length=150)),('id_sucursal', models.IntegerField(unique=True)),],),
                
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_fundacion', models.IntegerField()),
                ('cant_sucursales', models.IntegerField()),
                ('pais', models.CharField(max_length=100)),],),
                
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('peso', models.FloatField()),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('costo', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('empresa', models.CharField(max_length=150)),
                ('pasillo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='appsuper.pasillo')),],),
                
        migrations.AddField(model_name='pasillo',name='sucursal',field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasillos', to='appsuper.sucursal'),),
        
        migrations.CreateModel(
            name='Jefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('anos_servicio', models.IntegerField()),
                ('dni', models.IntegerField(unique=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefes', to='appsuper.sucursal')),],),
                
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin Nombre', max_length=150)),
                ('sexo', models.CharField(default='hombre', max_length=10)),
                ('edad', models.IntegerField()),('anos_servicio', models.IntegerField()),
                ('dni', models.IntegerField(unique=True)),
                ('id_empleado', models.IntegerField(unique=True)),
                ('sueldo', models.FloatField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='appsuper.sucursal')),],),
                
        migrations.AddField(model_name='sucursal',name='supermercado',field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='appsuper.supermercado'),),
        
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venta', models.IntegerField(unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cant_cuotas', models.IntegerField(default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appsuper.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appsuper.empleado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appsuper.producto')),],),
                
        # === 3. DISPARADORES DE CARGA (Al final de la lista de operaciones) ===
        
        migrations.RunPython(cargar_5_empleados_y_clientes),
        migrations.RunPython(cargar_productos_supermercado)]