# Generated by Django 5.2.7 on 2026-06-03 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsuper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='domicilio',
            field=models.CharField(default='Sin Domicilio', max_length=200),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(default='Sin Nombre', max_length=150),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cant_cuotas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(),
        ),
    ]
