# Generated by Django 5.2.7 on 2026-06-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsuper', '0002_alter_producto_peso_alter_producto_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('contado', 'Al contado'), ('tarjeta_credito', 'Con tarjeta de crédito'), ('tarjeta_debito', 'Con tarjeta de débito'), ('pago_internet', 'Pago vía Internet'), ('transferencia', 'Transferencia bancaria')], default='contado', max_length=30),
        ),
    ]
