# Generated by Django 6.0.6 on 2026-06-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsuper', '0004_venta_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sucursal_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('id_producto', 'sucursal_id')},
        ),
    ]
